Graspop/Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Graspop.Models
{
    public class Member
    {
        [Key]
        public Guid MemberId { get; set; }

        [Required]
        public string Name { get; set; }
        public string email { get; set; }
        public string gsm_nr { get; set; }

        public Guid PositionId { get; set; }
        public Position Position { get; set; }

        public Guid BandId { get; set; }
        public Band Band { get; set; } 
    }
}

Graspop/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Graspop.Data;
using Graspop.Models;
using Microsoft.AspNetCore.Authorization;

namespace Graspop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class MemberController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MemberController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Member/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .Include(m => m.Band)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Band/1/Member/Create
        public IActionResult Create(Guid? mainId, Guid? subId)
        {
            IEnumerable<Band> bands;

            if (subId == null)
            {
                bands = _context.Bands;
            } else
            {
                bands = _context.Bands.Where(b => b.BandId == subId);
                ViewData["BandId"] = subId;
            }

            ViewData["SelectListBand"] = new SelectList(bands, "BandId", "Name");
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Name");

            return View();
        }

        // POST: Member/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberId,Name,email,gsm_nr,PositionId,BandId")] Member member)
        {
            if (ModelState.IsValid)
            {
                member.MemberId = Guid.NewGuid();
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Band", new { id = member.BandId });
            }

            var bands = _context.Bands.Where(b => b.BandId == member.BandId);

            ViewData["BandId"] = new SelectList(bands, "BandId", "Name");
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Name", member.PositionId);
            return View(member);  
        }

        // GET: Member/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            ViewData["BandId"] = new SelectList(_context.Bands.Where(b => b.BandId == member.BandId), "BandId", "Name", member.BandId);
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Name", member.PositionId);
            return View(member);
        }

        // POST: Member/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("MemberId,Name,email,gsm_nr,PositionId,BandId")] Member member)
        {
            if (id != member.MemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Band", new { id = member.BandId });
            }
            ViewData["BandId"] = new SelectList(_context.Bands, "BandId", "Name", member.BandId);
            return View(member);
        }

        // GET: Member/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .Include(m => m.Band)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Member/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var member = await _context.Members.FindAsync(id);
            _context.Members.Remove(member);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Band", member.BandId);
        }

        private bool MemberExists(Guid id)
        {
            return _context.Members.Any(e => e.MemberId == id);
        }
    }
}

Graspop/Views/Member/Create.cshtml
@model Graspop.Models.Member

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Member">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gsm_nr" class="control-label"></label>
                <input asp-for="gsm_nr" class="form-control" />
                <span asp-validation-for="gsm_nr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BandId" class="control-label"></label>
                <select readonly="readonly" asp-for="BandId" class="form-control" asp-items="ViewBag.SelectListBand"></select>
            </div>
            <div class="form-group">
                <label asp-for="PositionId" class="control-label"></label>
                <select asp-for="PositionId" class="form-control" asp-items="ViewBag.PositionId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Band" asp-route-id="@ViewBag.BandId">Back to Band</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Graspop/Views/Member/Details.cshtml
@model Graspop.Models.Member

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gsm_nr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gsm_nr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Band)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Band.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Member" asp-action="Edit" asp-route-id="@Model.MemberId">Edit</a> |
    <a asp-controller="Band" asp-action="Details" asp-route-id="@Model.BandId">Back to Band</a>
</div>

Graspop/Views/Member/Edit.cshtml
@model Graspop.Models.Member

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Member" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gsm_nr" class="control-label"></label>
                <input asp-for="gsm_nr" class="form-control" />
                <span asp-validation-for="gsm_nr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BandId" class="control-label"></label>
                <select readonly="readonly" asp-for="BandId" class="form-control" asp-items="ViewBag.BandId"></select>
                <span asp-validation-for="BandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionId" class="control-label"></label>
                <select asp-for="PositionId" class="form-control" asp-items="ViewBag.PositionId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Band" asp-action="Details" asp-route-id="@Model.BandId">Back to Band</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}