Graspop/ViewModels/AddRoleViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Graspop.ViewModels
{
    public class AddRoleViewModel
    {
        [Required]
        [Display(Name = "Role name")]
        public string RoleName { get; set; }
    }
}

Graspop/ViewModels/AddUserViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Graspop.ViewModels
{
    public class AddUserViewModel
    {
        public AddUserViewModel()
        {
            this.Roles = new List<IdentityRole>();
        }

        [Required]
        public string RoleId { get; set; }

        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public List<IdentityRole> Roles { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

Graspop/ViewModels/EditUserViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Graspop.ViewModels
{
    public class EditUserViewModel
    {
        public string UserId { get; set; }
        public string UserRoleName { get; set; }
        public List<IdentityRole> Roles { get; set; }

        [Required(ErrorMessage = "Please enter the user name")]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password   { get; set; }
    }
}

Graspop/ViewModels/UserManagementViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Graspop.ViewModels
{
    public class UserManagementViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }

        public IList<string> Roles { get; set; }

    }

}

Graspop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Graspop.ViewModels;

namespace Graspop.Controllers
{
    [Authorize (Roles = "Administrator")]
    public class AdminController : Controller
    {
        private UserManager<IdentityUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public AdminController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this._userManager = userManager;
            this._roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UserManagement()
        {

            var users = this._userManager.Users.ToList();

            List<UserManagementViewModel> AllUsersAndRoles = new List<UserManagementViewModel>();

            foreach (var user in users)
            {
                var model = new UserManagementViewModel
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    Roles = await this._userManager.GetRolesAsync(user)
                };

                AllUsersAndRoles.Add(model);
            }


            return View(AllUsersAndRoles);
        }

        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if(user == null) {
                return RedirectToAction("UserManagement");
            }
            var roles = _roleManager.Roles;
            var userRole = await this._userManager.GetRolesAsync(user);
            var editUserViewModel = new EditUserViewModel()
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserRoleName = userRole[0],
                Roles = roles.ToList()
            };
            return View(editUserViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel editUserViewModel)
        {
            IdentityUser user = await _userManager.FindByIdAsync(editUserViewModel.UserId);

            if (user != null)
            { 
                if(!string.IsNullOrWhiteSpace(editUserViewModel.Password))
                {
                    await this._userManager.RemovePasswordAsync(user);
                    await this._userManager.AddPasswordAsync(user, editUserViewModel.Password);
                }
                var userRoles = await _userManager.GetRolesAsync(user);
                await this._userManager.RemoveFromRolesAsync(user, userRoles);
                await _userManager.AddToRoleAsync(user, editUserViewModel.UserRoleName);
            }
            else
            {
                ModelState.AddModelError("", "This user can't be found");
            }

            return RedirectToAction("UserManagement");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("UserManagement");
                else
                    ModelState.AddModelError("", "Something went wrong while deleting this user.");
            }
            else
            {
                ModelState.AddModelError("", "This user can't be found");
            }
            return View("UserManagement");
        }

        public IActionResult RoleManagement()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        public IActionResult AddRole() => View();

        [HttpPost]
        public async Task<IActionResult> AddRole(AddRoleViewModel addRoleViewModel)
        {

            if (!ModelState.IsValid) return View(addRoleViewModel);

            var role = new IdentityRole
            {
                Name = addRoleViewModel.RoleName
            };

            IdentityResult result = await _roleManager.CreateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("RoleManagement");
            }

            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(addRoleViewModel);
        }

        public IActionResult AddUser()
        {
            var roles = _roleManager.Roles;
            var addUserViewModel =  new AddUserViewModel()
            {
                Roles = roles.ToList()
            };
            return View(addUserViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(AddUserViewModel addUserViewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddUser");
            }

            var user = new IdentityUser()
            {
                UserName = addUserViewModel.UserName
            };

            IdentityResult result = await _userManager.CreateAsync(user, addUserViewModel.Password);

            if (result.Succeeded)
            {
                var newUser = await _userManager.FindByNameAsync(addUserViewModel.UserName);
                var role = await _roleManager.FindByIdAsync(addUserViewModel.RoleId);
                var roleResult = await _userManager.AddToRoleAsync(user, role.Name);

                if (roleResult.Succeeded)
                {
                    return RedirectToAction("UserManagement");
                }

                foreach (IdentityError error in roleResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            var roles = _roleManager.Roles;
            addUserViewModel.Roles = roles.ToList();

            return View(addUserViewModel);
        }
    }
}

Graspop/Controllers/BandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Graspop.Data;
using Graspop.Models;
using Graspop.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Graspop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BandController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BandController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Band
        public async Task<IActionResult> Index()
        {
            return View(await _context.Bands.ToListAsync());
        }

        // GET: Band/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var band = await _context.Bands.Include(b => b.Members).ThenInclude(b => b.Position).FirstOrDefaultAsync(b => b.BandId == id);
            if (band == null)
            {
                return NotFound();
            }

            return View(band);
        }

        // GET: Band/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Band/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BandId,Name")] Band band)
        {
            if (ModelState.IsValid)
            {
                band.BandId = Guid.NewGuid();
                _context.Add(band);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(band);
        }

        // GET: Band/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var band = await _context.Bands.FindAsync(id);
            if (band == null)
            {
                return NotFound();
            }
            return View(band);
        }

        // POST: Band/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("BandId,Name")] Band band)
        {
            if (id != band.BandId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(band);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BandExists(band.BandId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(band);
        }

        // GET: Band/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var band = await _context.Bands
                .FirstOrDefaultAsync(m => m.BandId == id);
            if (band == null)
            {
                return NotFound();
            }

            return View(band);
        }

        // POST: Band/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var band = await _context.Bands.FindAsync(id);
            _context.Bands.Remove(band);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BandExists(Guid id)
        {
            return _context.Bands.Any(e => e.BandId == id);
        }
    }
}

Graspop/Controllers/TentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Graspop.Data;
using Graspop.Models;
using Microsoft.AspNetCore.Authorization;

namespace Graspop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class TentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TentController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tent
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tents.ToListAsync());
        }

        // GET: Tent/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tent = await _context.Tents
                .FirstOrDefaultAsync(m => m.TentId == id);
            if (tent == null)
            {
                return NotFound();
            }

            return View(tent);
        }

        // GET: Tent/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TentId,Name")] Tent tent)
        {
            if (ModelState.IsValid)
            {
                tent.TentId = Guid.NewGuid();
                _context.Add(tent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tent);
        }

        // GET: Tent/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tent = await _context.Tents.FindAsync(id);
            if (tent == null)
            {
                return NotFound();
            }
            return View(tent);
        }

        // POST: Tent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("TentId,Name")] Tent tent)
        {
            if (id != tent.TentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TentExists(tent.TentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tent);
        }

        // GET: Tent/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tent = await _context.Tents
                .FirstOrDefaultAsync(m => m.TentId == id);
            if (tent == null)
            {
                return NotFound();
            }

            return View(tent);
        }

        // POST: Tent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var tent = await _context.Tents.FindAsync(id);
            _context.Tents.Remove(tent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TentExists(Guid id)
        {
            return _context.Tents.Any(e => e.TentId == id);
        }
    }
}

Graspop/Views/Admin/AddRole.cshtml
@model AddRoleViewModel

<h2>Create a new role</h2>

<form asp-controller="Admin" asp-action="AddRole" method="post" class="form-horizontal" role="form">
    <h4>Enter the role details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="RoleName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-primary">Create role</button>
        </div>
    </div>
</form>

Graspop/Views/Admin/AddUser.cshtml
@model AddUserViewModel

<h2>Create a new user</h2>

<form asp-controller="Admin" asp-action="AddUser" method="post" class="form-horizontal" role="form">
    <h4>Enter the user details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="RoleId" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="form-control" asp-for="RoleId" asp-items="@(new SelectList(Model.Roles, "Id", "Name"))"></select>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="UserName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-success">Create user</button>
            <a asp-action="UserManagement" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>

Graspop/Views/Admin/EditUser.cshtml
@model EditUserViewModel

<h2>Edit a user</h2>

<form asp-controller="Admin" asp-action="EditUser" method="post" class="form-horizontal" role="form"  autocomplete="off">
    <h4>Enter the user details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="UserId" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="UserId" class="form-control" readonly="readonly" />
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="UserName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="UserName" class="form-control" readonly="readonly" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="UserRoleName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="form-control" asp-for="UserRoleName" asp-items="@(new SelectList(Model.Roles, "Name", "Name", Model.UserRoleName))">
            </select>
        </div>
    </div>
    
    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" value="" />
            <small>Leave empty if you don't want to change the password.</small>
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-success">Edit user</button>
            <a asp-action="UserManagement" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>

Graspop/Views/Admin/Index.cshtml
<h2>Bookings</h2>
<hr />
<div class="list-group">
    <div class="outer">
        <a class="list-group-item list-group-item-action" asp-controller="Booking" asp-action="Index">Bookings</a></div>
    </div>
<br /><br />
<h2>Manage</h2>
<hr />
<div class="list-group">
    <div class="outer"><a class="list-group-item list-group-item-action" asp-controller="Admin" asp-action="UserManagement">Users</a></div>
    <div class="outer"><a class="list-group-item list-group-item-action" asp-controller="Band" asp-action="Index">Bands</a></div>
    <div class="outer"><a class="list-group-item list-group-item-action" asp-controller="Tent" asp-action="Index">Tents</a></div>
    <div class="outer"><a class="list-group-item list-group-item-action" asp-controller="Position" asp-action="Index">Positions</a></div>
    <div class="outer"><a class="list-group-item list-group-item-action" asp-controller="Stage" asp-action="Index">Stages</a></div>
    <div class="outer"><a class="list-group-item list-group-item-action" asp-controller="DressingRoom" asp-action="Index">Dressing rooms</a></div>
</div>

Graspop/Views/Admin/UserManagement.cshtml
@model List<UserManagementViewModel>

<h2>User management</h2>

<div asp-validation-summary="All" class="text-danger"></div>
    <table class="table table-condensed table-bordered" header header-content="User Management">
        <tr>
            <th>User name</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
        @if (Model.Any())
        {
            @foreach (var user in Model)
            {
            <tr>
                <td>@user.UserName</td>
                <td>
                    @foreach (var role in user.Roles)
                    {
                        @role
                    }
                </td>
                <td>
                    <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                        <button type="submit" onclick="return confirm('Do you really want to delete this user?');" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
            }
        }
        else
        {
            <tr><td colspan="4" class="text-center">No User Accounts</td></tr>
        }

    </table>


<p>
    <a class="btn btn-primary" asp-action="AddUser">Add new user</a>
</p>